import Foundation
import UseCaseSDK

public struct CreateChainProjectUseCase: UseCase {

    public struct Options: Sendable {
        public let assignee: String?
        public let baseBranch: String
        public let name: String
        public let repoPath: URL

        public init(name: String, repoPath: URL, baseBranch: String = "main", assignee: String? = nil) {
            self.assignee = assignee
            self.baseBranch = baseBranch
            self.name = name
            self.repoPath = repoPath
        }
    }

    public init() {}

    public func run(options: Options) throws {
        let sanitized = options.name.lowercased().replacingOccurrences(of: " ", with: "-")
        let projectDir = options.repoPath
            .appendingPathComponent("claude-chain")
            .appendingPathComponent(sanitized)

        guard !FileManager.default.fileExists(atPath: projectDir.path) else {
            throw CreateChainProjectError.projectAlreadyExists(sanitized)
        }

        try FileManager.default.createDirectory(at: projectDir, withIntermediateDirectories: true)

        let displayName = sanitized.replacingOccurrences(of: "-", with: " ").capitalized
        let specContent = """
        # \(displayName)

        ## Tasks

        - [ ] Add your first task here
        """
        try specContent.write(to: projectDir.appendingPathComponent("spec.md"), atomically: true, encoding: .utf8)

        var configLines: [String] = []
        if options.baseBranch != "main" {
            configLines.append("baseBranch: \(options.baseBranch)")
        }
        if let assignee = options.assignee, !assignee.isEmpty {
            configLines.append("assignee: \(assignee)")
        }
        if !configLines.isEmpty {
            try (configLines.joined(separator: "\n") + "\n")
                .write(to: projectDir.appendingPathComponent("configuration.yml"), atomically: true, encoding: .utf8)
        }

        let templateContent = """
        ## Task

        {{TASK_DESCRIPTION}}

        ## Review Checklist

        - [ ] Code follows project conventions
        - [ ] Tests pass
        - [ ] No unintended changes

        ---
        *Auto-generated by ClaudeChain*
        """
        try templateContent.write(to: projectDir.appendingPathComponent("pr-template.md"), atomically: true, encoding: .utf8)

        let preActionURL = projectDir.appendingPathComponent("pre-action.sh")
        try "#!/bin/bash\n# Pre-action script\necho \"Pre-action script completed successfully\"\n"
            .write(to: preActionURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: preActionURL.path)

        let postActionURL = projectDir.appendingPathComponent("post-action.sh")
        try "#!/bin/bash\n# Post-action script\necho \"Post-action script completed successfully\"\n"
            .write(to: postActionURL, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: postActionURL.path)
    }
}

public enum CreateChainProjectError: LocalizedError {
    case projectAlreadyExists(String)

    public var errorDescription: String? {
        switch self {
        case .projectAlreadyExists(let name):
            return "Project '\(name)' already exists."
        }
    }
}
